import { Product } from '../types';

// Smoocho Menu Products - Exact from Menu Images
export const smoochoProducts: Omit<Product, 'created_at' | 'updated_at'>[] = [
  // Kunafa Bowls (12 items)
  {
    id: 'prod-1',
    name: 'Hazelnut Kunafa',
    description: 'Premium kunafa with hazelnut toppings',
    category_id: 'cat-1',
    price: 219,
    cost_price: 110,
    sku: 'KUN001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 10,
  },
  {
    id: 'prod-2',
    name: 'White Chocolate Kunafa',
    description: 'Kunafa topped with white chocolate',
    category_id: 'cat-1',
    price: 219,
    cost_price: 110,
    sku: 'KUN002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 10,
  },
  {
    id: 'prod-3',
    name: 'Pista Kunafa',
    description: 'Kunafa with pistachio toppings',
    category_id: 'cat-1',
    price: 249,
    cost_price: 125,
    sku: 'KUN003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 10,
  },
  {
    id: 'prod-4',
    name: 'Biscoff Kunafa',
    description: 'Kunafa with biscoff cookie crumbs',
    category_id: 'cat-1',
    price: 209,
    cost_price: 105,
    sku: 'KUN004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 10,
  },
  {
    id: 'prod-5',
    name: 'Hazelnut White Kunafa',
    description: 'Kunafa with hazelnut and white chocolate',
    category_id: 'cat-1',
    price: 249,
    cost_price: 125,
    sku: 'KUN005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 10,
  },
  {
    id: 'prod-6',
    name: 'Biscoff Hazelnut Kunafa',
    description: 'Kunafa with biscoff and hazelnut',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 10,
  },
  {
    id: 'prod-7',
    name: 'Pista White Kunafa',
    description: 'Kunafa with pistachio and white chocolate',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN007',
    is_available: true,
    is_active: true,
    sort_order: 7,
    preparation_time: 10,
  },
  {
    id: 'prod-8',
    name: 'Hazelnut Pista Kunafa',
    description: 'Kunafa with hazelnut and pistachio',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN008',
    is_available: true,
    is_active: true,
    sort_order: 8,
    preparation_time: 10,
  },
  {
    id: 'prod-9',
    name: 'Biscoff White Kunafa',
    description: 'Kunafa with biscoff and white chocolate',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN009',
    is_available: true,
    is_active: true,
    sort_order: 9,
    preparation_time: 10,
  },
  {
    id: 'prod-10',
    name: 'Pista Biscoff Kunafa',
    description: 'Kunafa with pistachio and biscoff',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN010',
    is_available: true,
    is_active: true,
    sort_order: 10,
    preparation_time: 10,
  },
  {
    id: 'prod-11',
    name: 'Coffee Hazelnut Kunafa',
    description: 'Coffee flavored kunafa with hazelnut',
    category_id: 'cat-1',
    price: 249,
    cost_price: 125,
    sku: 'KUN011',
    is_available: true,
    is_active: true,
    sort_order: 11,
    preparation_time: 10,
  },
  {
    id: 'prod-12',
    name: 'Pista Coffee Kunafa',
    description: 'Coffee flavored kunafa with pistachio',
    category_id: 'cat-1',
    price: 259,
    cost_price: 130,
    sku: 'KUN012',
    is_available: true,
    is_active: true,
    sort_order: 12,
    preparation_time: 10,
  },

  // Smoocho Signatures (9 items)
  {
    id: 'prod-13',
    name: 'Choco Tsunami',
    description: 'Signature chocolate dessert creation',
    category_id: 'cat-2',
    price: 189,
    cost_price: 95,
    sku: 'SIG001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 12,
  },
  {
    id: 'prod-14',
    name: 'Mango Tsunami',
    description: 'Signature mango dessert creation',
    category_id: 'cat-2',
    price: 199,
    cost_price: 100,
    sku: 'SIG002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 12,
  },
  {
    id: 'prod-15',
    name: 'Hazelnut Mango Cyclone',
    description: 'Hazelnut and mango signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 12,
  },
  {
    id: 'prod-16',
    name: 'Pista Mango Thunderstorm',
    description: 'Pistachio and mango signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 12,
  },
  {
    id: 'prod-17',
    name: 'Biscoff Mango Hurricane',
    description: 'Biscoff and mango signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 12,
  },
  {
    id: 'prod-18',
    name: 'Pista Hazelnut Earthquake',
    description: 'Pistachio and hazelnut signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 12,
  },
  {
    id: 'prod-19',
    name: 'Pista Biscoff Tsunami',
    description: 'Pistachio and biscoff signature dessert',
    category_id: 'cat-2',
    price: 249,
    cost_price: 125,
    sku: 'SIG007',
    is_available: true,
    is_active: true,
    sort_order: 7,
    preparation_time: 12,
  },
  {
    id: 'prod-20',
    name: 'Coffee Mango Cyclone',
    description: 'Coffee and mango signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG008',
    is_available: true,
    is_active: true,
    sort_order: 8,
    preparation_time: 12,
  },
  {
    id: 'prod-21',
    name: 'Pista Coffee Earthquake',
    description: 'Pistachio and coffee signature dessert',
    category_id: 'cat-2',
    price: 209,
    cost_price: 105,
    sku: 'SIG009',
    is_available: true,
    is_active: true,
    sort_order: 9,
    preparation_time: 12,
  },

  // Crispy Rice Tubs
  {
    id: 'prod-27',
    name: 'Hazelnut Rice Tub',
    description: 'Crispy rice with hazelnut toppings',
    category_id: 'cat-3',
    price: 199,
    cost_price: 100,
    sku: 'RIC001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 8,
  },
  {
    id: 'prod-28',
    name: 'White Chocolate Rice Tub',
    description: 'Crispy rice with white chocolate',
    category_id: 'cat-3',
    price: 199,
    cost_price: 100,
    sku: 'RIC002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 8,
  },
  {
    id: 'prod-29',
    name: 'Pista Rice Tub',
    description: 'Crispy rice with pistachio toppings',
    category_id: 'cat-3',
    price: 219,
    cost_price: 110,
    sku: 'RIC003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 8,
  },
  {
    id: 'prod-30',
    name: 'Biscoff Rice Tub',
    description: 'Crispy rice with biscoff crumbs',
    category_id: 'cat-3',
    price: 189,
    cost_price: 95,
    sku: 'RIC004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 8,
  },
  {
    id: 'prod-31',
    name: 'Mixed Nuts Rice Tub',
    description: 'Crispy rice with mixed nuts',
    category_id: 'cat-3',
    price: 229,
    cost_price: 115,
    sku: 'RIC005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 8,
  },

  // Choco Desserts
  {
    id: 'prod-32',
    name: 'Dark Chocolate Brownie',
    description: 'Rich dark chocolate brownie',
    category_id: 'cat-4',
    price: 149,
    cost_price: 75,
    sku: 'CHO001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 5,
  },
  {
    id: 'prod-33',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate lava cake',
    category_id: 'cat-4',
    price: 169,
    cost_price: 85,
    sku: 'CHO002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 10,
  },
  {
    id: 'prod-34',
    name: 'Chocolate Mousse Cup',
    description: 'Creamy chocolate mousse',
    category_id: 'cat-4',
    price: 129,
    cost_price: 65,
    sku: 'CHO003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 3,
  },
  {
    id: 'prod-35',
    name: 'Chocolate Truffle Cake',
    description: 'Decadent chocolate truffle cake',
    category_id: 'cat-4',
    price: 189,
    cost_price: 95,
    sku: 'CHO004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 8,
  },
  {
    id: 'prod-36',
    name: 'Hot Chocolate Fudge',
    description: 'Warm chocolate fudge dessert',
    category_id: 'cat-4',
    price: 159,
    cost_price: 80,
    sku: 'CHO005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 6,
  },

  // Fruits Choco Mix
  {
    id: 'prod-40',
    name: 'Strawberry Chocolate Delight',
    description: 'Fresh strawberries with chocolate',
    category_id: 'cat-5',
    price: 179,
    cost_price: 90,
    sku: 'FRU001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 8,
  },
  {
    id: 'prod-41',
    name: 'Mango Chocolate Fusion',
    description: 'Ripe mangoes with premium chocolate',
    category_id: 'cat-5',
    price: 199,
    cost_price: 100,
    sku: 'FRU002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 8,
  },
  {
    id: 'prod-42',
    name: 'Mixed Berry Chocolate Bowl',
    description: 'Mixed berries with dark chocolate',
    category_id: 'cat-5',
    price: 219,
    cost_price: 110,
    sku: 'FRU003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 10,
  },
  {
    id: 'prod-43',
    name: 'Banana Chocolate Parfait',
    description: 'Sliced bananas layered with chocolate',
    category_id: 'cat-5',
    price: 159,
    cost_price: 80,
    sku: 'FRU004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 8,
  },
  {
    id: 'prod-44',
    name: 'Kiwi White Chocolate Mix',
    description: 'Fresh kiwi with white chocolate',
    category_id: 'cat-5',
    price: 189,
    cost_price: 95,
    sku: 'FRU005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 8,
  },
  {
    id: 'prod-45',
    name: 'Pineapple Choco Chunks',
    description: 'Grilled pineapple with chocolate chunks',
    category_id: 'cat-5',
    price: 169,
    cost_price: 85,
    sku: 'FRU006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 10,
  },

  // Ice Creams
  {
    id: 'prod-46',
    name: 'Vanilla Scoop',
    description: 'Premium vanilla ice cream',
    category_id: 'cat-6',
    price: 89,
    cost_price: 45,
    sku: 'ICE001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 2,
  },
  {
    id: 'prod-47',
    name: 'Chocolate Scoop',
    description: 'Rich chocolate ice cream',
    category_id: 'cat-6',
    price: 89,
    cost_price: 45,
    sku: 'ICE002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 2,
  },
  {
    id: 'prod-48',
    name: 'Strawberry Scoop',
    description: 'Fresh strawberry ice cream',
    category_id: 'cat-6',
    price: 99,
    cost_price: 50,
    sku: 'ICE003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 2,
  },
  {
    id: 'prod-49',
    name: 'Mango Scoop',
    description: 'Tropical mango ice cream',
    category_id: 'cat-6',
    price: 99,
    cost_price: 50,
    sku: 'ICE004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 2,
  },
  {
    id: 'prod-50',
    name: 'Pistachio Scoop',
    description: 'Premium pistachio ice cream',
    category_id: 'cat-6',
    price: 109,
    cost_price: 55,
    sku: 'ICE005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 2,
  },
  {
    id: 'prod-51',
    name: 'Coffee Scoop',
    description: 'Rich coffee flavored ice cream',
    category_id: 'cat-6',
    price: 99,
    cost_price: 50,
    sku: 'ICE006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 2,
  },
  {
    id: 'prod-52',
    name: 'Cookies & Cream Scoop',
    description: 'Cookies and cream ice cream',
    category_id: 'cat-6',
    price: 109,
    cost_price: 55,
    sku: 'ICE007',
    is_available: true,
    is_active: true,
    sort_order: 7,
    preparation_time: 2,
  },
  {
    id: 'prod-53',
    name: 'Kulfi Scoop',
    description: 'Traditional Indian kulfi',
    category_id: 'cat-6',
    price: 119,
    cost_price: 60,
    sku: 'ICE008',
    is_available: true,
    is_active: true,
    sort_order: 8,
    preparation_time: 2,
  },

  // Beverages
  {
    id: 'prod-54',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    category_id: 'cat-7',
    price: 79,
    cost_price: 40,
    sku: 'BEV001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 3,
  },
  {
    id: 'prod-55',
    name: 'Mango Lassi',
    description: 'Creamy mango yogurt drink',
    category_id: 'cat-7',
    price: 89,
    cost_price: 45,
    sku: 'BEV002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 4,
  },
  {
    id: 'prod-56',
    name: 'Cold Coffee',
    description: 'Iced coffee with milk',
    category_id: 'cat-7',
    price: 99,
    cost_price: 50,
    sku: 'BEV003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 5,
  },
  {
    id: 'prod-57',
    name: 'Chocolate Milkshake',
    description: 'Rich chocolate milkshake',
    category_id: 'cat-7',
    price: 119,
    cost_price: 60,
    sku: 'BEV004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 6,
  },
  {
    id: 'prod-58',
    name: 'Strawberry Shake',
    description: 'Fresh strawberry milkshake',
    category_id: 'cat-7',
    price: 109,
    cost_price: 55,
    sku: 'BEV005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 6,
  },
  {
    id: 'prod-59',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime soda',
    category_id: 'cat-7',
    price: 69,
    cost_price: 35,
    sku: 'BEV006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 3,
  },
  {
    id: 'prod-60',
    name: 'Mint Lemonade',
    description: 'Fresh mint and lemon drink',
    category_id: 'cat-7',
    price: 79,
    cost_price: 40,
    sku: 'BEV007',
    is_available: true,
    is_active: true,
    sort_order: 7,
    preparation_time: 4,
  },
  {
    id: 'prod-61',
    name: 'Masala Chai',
    description: 'Traditional spiced tea',
    category_id: 'cat-7',
    price: 49,
    cost_price: 25,
    sku: 'BEV008',
    is_available: true,
    is_active: true,
    sort_order: 8,
    preparation_time: 5,
  },
  {
    id: 'prod-62',
    name: 'Filter Coffee',
    description: 'South Indian filter coffee',
    category_id: 'cat-7',
    price: 59,
    cost_price: 30,
    sku: 'BEV009',
    is_available: true,
    is_active: true,
    sort_order: 9,
    preparation_time: 4,
  },
  {
    id: 'prod-63',
    name: 'Buttermilk',
    description: 'Spiced buttermilk drink',
    category_id: 'cat-7',
    price: 59,
    cost_price: 30,
    sku: 'BEV010',
    is_available: true,
    is_active: true,
    sort_order: 10,
    preparation_time: 3,
  },

  // Add-ons
  {
    id: 'prod-64',
    name: 'Extra Hazelnut',
    description: 'Additional hazelnut topping',
    category_id: 'cat-8',
    price: 39,
    cost_price: 20,
    sku: 'ADD001',
    is_available: true,
    is_active: true,
    sort_order: 1,
    preparation_time: 1,
  },
  {
    id: 'prod-65',
    name: 'Extra Pistachio',
    description: 'Additional pistachio topping',
    category_id: 'cat-8',
    price: 49,
    cost_price: 25,
    sku: 'ADD002',
    is_available: true,
    is_active: true,
    sort_order: 2,
    preparation_time: 1,
  },
  {
    id: 'prod-66',
    name: 'Extra White Chocolate',
    description: 'Additional white chocolate topping',
    category_id: 'cat-8',
    price: 39,
    cost_price: 20,
    sku: 'ADD003',
    is_available: true,
    is_active: true,
    sort_order: 3,
    preparation_time: 1,
  },
  {
    id: 'prod-67',
    name: 'Extra Biscoff',
    description: 'Additional biscoff crumbs',
    category_id: 'cat-8',
    price: 35,
    cost_price: 18,
    sku: 'ADD004',
    is_available: true,
    is_active: true,
    sort_order: 4,
    preparation_time: 1,
  },
  {
    id: 'prod-68',
    name: 'Extra Honey',
    description: 'Premium honey drizzle',
    category_id: 'cat-8',
    price: 25,
    cost_price: 13,
    sku: 'ADD006',
    is_available: true,
    is_active: true,
    sort_order: 6,
    preparation_time: 1,
  },
  {
    id: 'prod-69',
    name: 'Extra Chocolate Sauce',
    description: 'Rich chocolate sauce',
    category_id: 'cat-8',
    price: 29,
    cost_price: 15,
    sku: 'ADD007',
    is_available: true,
    is_active: true,
    sort_order: 7,
    preparation_time: 1,
  },
  {
    id: 'prod-70',
    name: 'Extra Ice Cream Scoop',
    description: 'Additional ice cream scoop for sharing',
    category_id: 'cat-8',
    price: 29,
    cost_price: 15,
    sku: 'ADD005',
    is_available: true,
    is_active: true,
    sort_order: 5,
    preparation_time: 1,
  },
];
